<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acceptanceofgoods' => 'Приемка',
    'Adress' => 'Адрес',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись',
    'Count' => 'Количество',
    'Create Acceptanceofgoods' => 'Добавить приемку',
    'Create Employee' => 'Добавить сотрудника',
    'Create Foodstorage' => 'Добавить место хранения',
    'Create Order' => 'Добавить заказ',
    'Create Pruducts' => 'Добавить продукт',
    'Create Standards' => 'Добавить требование',
    'Create Storehouse' => 'Добавить склад',
    'Create Transporter' => 'Добавить перевозчика',
    'Create Typeofvendor' => 'Добавить тип поставщика',
    'Create Vendor' => 'Добавить поставщика',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Deliverytime' => 'Дата доставки',
    'Employee Idemployee' => 'Сотрудник',
    'Employees' => 'Сотрудники',
    'EmpName' => 'ФИО сотрудника',
    'Foodstorages' => 'Места хранения',
    'Freshness' => 'Свежесть',
    'Idacceptanceofgoods' => 'Номер',
    'Idemployee' => 'Номер',
    'Idfoodstorage' => 'Номер',
    'Idorder' => 'НоНомермер',
    'Idpruduct' => 'Номер',
    'Idstandards' => 'Номер',
    'Idstorehouse' => 'Номер',
    'Idtransporter' => 'Номер',
    'Idtypeofvendor' => 'Номер',
    'Idvendor' => 'Номер',
    'Info' => 'Информация',
    'Name' => 'Наименование',
    'Number' => 'Номер',
    'Order Idorder' => 'Заказ',
    'Ordercol' => '',
    'Orders' => 'Заказы',
    'Phone' => 'Номер телефона',
    'Pruducts' => 'Сырье',
    'Pruducts Idpruduct' => 'Сырье',
    'Racknumber' => 'Номер стеллажа',
    'Refrigeratornumber' => 'Номер холодильной камеры',
    'Save' => 'Сохранить',
    'Size' => 'Размер',
    'Standards' => 'Требования',
    'Standards Idstandards' => 'Требования',
    'Storehouse Idstorehouse' => 'Склад',
    'Storehouses' => 'Склады',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Transporter Idtransporter' => 'Перевозчик',
    'Transporters' => 'Перевозчики',
    'Typeofvendor Idtypeofvendor' => '',
    'Typeofvendors' => 'Типы поставщиков',
    'Units' => 'Единицы измерения',
    'Update' => 'Обновить',
    'Update Acceptanceofgoods: {name}' => 'Обносить приемку: {name}',
    'Update Employee: {name}' => 'Обновить данные сотрудника: {name}',
    'Update Foodstorage: {name}' => 'Обновить данные хранения товара: {name}',
    'Update Order: {name}' => 'Обновить данные заказа: {name}',
    'Update Pruducts: {name}' => 'Обновить данные продукта: {name}',
    'Update Standards: {name}' => 'Обновить требования: {name}',
    'Update Storehouse: {name}' => 'Обновить данные склада: {name}',
    'Update Transporter: {name}' => 'Обновить данные перевозчика: {name}',
    'Update Typeofvendor: {name}' => 'Обновить тип поставщика: {name}',
    'Update Vendor: {name}' => 'Обновить данные поставщика: {name}',
    'Vendor Idvendor' => 'Поставщик',
    'Vendors' => 'Поставщики',
];
