<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acceptmaterials' => 'Приемки',
    'Actnumber' => 'Номер акта',
    'Adress' => 'Адрес',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись?',
    'Categoryname' => 'Название категории',
    'Cost' => 'Стоимость',
    'Count' => 'Количество',
    'Create Acceptmaterial' => 'Добавить приемку',
    'Create Employee' => 'Добавить сотрудника',
    'Create Inventarisation' => 'Добавить запись',
    'Create Material' => 'Добавить материал',
    'Create Materialcategory' => 'Добавить категорию материала',
    'Create Materialstorage' => 'Добавить место хранения материала',
    'Create Storehouse' => 'Добавить склад',
    'Create Transporter' => 'Добавить перевозчика',
    'Create Vendor' => 'Добавить поставщика',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Employee' => 'Сотрудник',
    'Employee Idemployee' => 'Сотрудник',
    'Employees' => 'Сотрудники',
    'Idaccept' => '',
    'Idemployee' => '',
    'Idfoodstorage' => '',
    'Idinventarisation' => '',
    'Idmaterial' => '',
    'Idmaterialcategory' => '',
    'Idstorehouse' => '',
    'Idtransporter' => '',
    'Idvendor' => '',
    'Info' => 'Информация',
    'Inventarisations' => 'Инвентаризация',
    'Invnumber' => 'Инвентарный номер',
    'Material' => 'Материал',
    'Materialcategories' => 'Категории материалов',
    'Materialcategory' => 'Категория материала',
    'Materials' => 'Материалы',
    'Materialstorages' => 'Места хранения материалов',
    'EmpName' => 'ФИО',
    'MaterialName' => 'Наименование материала',
    'StorehouseName' => 'Наименование склада',
    'Name' => 'Наименование',
    'Phone' => 'Номер телефона',
    'Protocolnumber' => 'Номер протокола',
    'Racknumber' => 'Номер стеллажа',
    'Reset' => 'Отменить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Storehouse' => 'Склад',
    'Storehouses' => 'Склады',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Transporter' => 'Перевозчик',
    'Transporters' => 'Перевозчики',
    'Units' => 'Единицы измерения',
    'Update' => 'Обновить',
    'Password' => 'Пароль',
    'Username' => 'Имя пользователя',
    'Remember Me' => 'Запомнить меня',
    'Update Acceptmaterial: {name}' => '',
    'Update Employee: {name}' => '',
    'Update Inventarisation: {name}' => '',
    'Update Material: {name}' => '',
    'Update Materialcategory: {name}' => '',
    'Update Materialstorage: {name}' => '',
    'Update Storehouse: {name}' => '',
    'Update Transporter: {name}' => '',
    'Update Vendor: {name}' => '',
    'Vendor' => 'Поставщик',
    'Vendors' => 'Поставщики',
];
